### ISSUE TITLE
IOexception when downloading file

### ISSUE THREAD

**Issue by swapniladsure** [RaghavSood/AppaholicsUpdateChecker#1]
Solved the problem just giving permission to write external device. 

I am trying to call update and install method from my activity and i pass url "https://apps.mycompany.com/testing/update/myapp.apk"
But it is showing me error of "There was IOException while downloading file"
Also it display error message on device the " There was problem parsing the package"
I have use StrictMode in my activity . 
It display progress bar and immediately display this error dialog.
any suggestion.i am testing it on galaxy nexus

**Comment by RaghavSood** [comment]
Your app must have:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
